from enum import Enum


class LabelEnum_aht(str, Enum):
    aht_dogbro = 'aht_dogbro'
    aht_earn_fcash = 'aht_earn_fcash'
    aht_earn_pcoin = 'aht_earn_pcoin'
    aht_evacuation_point_check_box = 'aht_evacuation_point_check_box'
    aht_loc_check_box = 'aht_loc_check_box'
    aht_loc_check_box_another = 'aht_loc_check_box_another'
    aht_mint = 'aht_mint'
    aht_pick_the_lock_check_box = 'aht_pick_the_lock_check_box'
    aht_pick_the_lock_plus_check_box = 'aht_pick_the_lock_plus_check_box'
    aht_portal_full = 'aht_portal_full'
    aht_portal_half = 'aht_portal_half'
    aht_rank_box = 'aht_rank_box'
    aht_rank_exit_confirm = 'aht_rank_exit_confirm'
    aht_safe_box_exist_check_box = 'aht_safe_box_exist_check_box'
    aht_sakiri = 'aht_sakiri'
    aht_start_check_box = 'aht_start_check_box'
    aht_tp_done = 'aht_tp_done'
    cf_cafe = 'cf_cafe'
    cf_express = 'cf_express'
    cf_fishing = 'cf_fishing'
    cf_heist = 'cf_heist'
    cf_live = 'cf_live'
    cf_mahjong = 'cf_mahjong'
    cf_racing = 'cf_racing'
    cf_taxi = 'cf_taxi'
    cf_tetris = 'cf_tetris'
    f5_cafe = 'f5_cafe'
    f5_cityfun = 'f5_cityfun'
    f5_garage = 'f5_garage'
    f5_homes = 'f5_homes'
    f5_racing = 'f5_racing'
    relife_check_box = 'relife_check_box'
    relife_confirm = 'relife_confirm'
    safe_box_does_not_exist_check_box = 'safe_box_does_not_exist_check_box'
